# Generated by Django 4.2.17 on 2026-03-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insights', '0001_initial'),
        ('organizations', '0001_initial'),
        ('evidence', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('problem_statement', models.TextField()),
                ('affected_segments', models.JSONField(blank=True, default=list)),
                ('proposed_solution', models.TextField(blank=True)),
                ('assumptions', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('implementation_outline', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('discovered', 'Discovered'), ('evaluating', 'Evaluating'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('shipped', 'Shipped'), ('rejected', 'Rejected')], default='discovered', max_length=20)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('evidence_refs', models.ManyToManyField(blank=True, related_name='opportunities', to='evidence.rawevidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
                ('supporting_insights', models.ManyToManyField(blank=True, related_name='opportunities', to='insights.insightcluster')),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric_type', models.CharField(choices=[('adoption', 'Adoption'), ('retention', 'Retention'), ('revenue', 'Revenue'), ('engagement', 'Engagement'), ('support_tickets', 'Support Tickets')], max_length=50)),
                ('predicted_value', models.FloatField(default=0)),
                ('actual_value', models.FloatField(blank=True, null=True)),
                ('measured_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'outcome_metrics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityScore',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequency_score', models.FloatField(default=0, help_text='0-10')),
                ('revenue_impact', models.FloatField(default=0, help_text='0-10')),
                ('retention_impact', models.FloatField(default=0, help_text='0-10')),
                ('strategic_alignment', models.FloatField(default=0, help_text='0-10')),
                ('effort_estimate', models.FloatField(default=0, help_text='0-10, higher = more effort')),
                ('confidence_score', models.FloatField(default=0, help_text='0-1')),
                ('total_score', models.FloatField(default=0)),
                ('weights_used', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'opportunity_scores',
                'ordering': ['-total_score'],
            },
        ),
    ]
