# Generated by Django 4.2.17 on 2026-03-14 03:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
        ('codebase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubIntegration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_user_id', models.BigIntegerField()),
                ('github_username', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('_access_token', models.BinaryField(db_column='access_token_encrypted', help_text='Fernet-encrypted GitHub OAuth token')),
                ('scopes', models.CharField(blank=True, default='repo,read:user,user:email', max_length=500)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'github_integrations',
                'ordering': ['-connected_at'],
                'unique_together': {('organization', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GitHubRepository',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_repo_id', models.BigIntegerField()),
                ('repo_name', models.CharField(max_length=255)),
                ('repo_full_name', models.CharField(max_length=500)),
                ('repo_url', models.URLField()),
                ('clone_url', models.URLField(blank=True)),
                ('default_branch', models.CharField(default='main', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('language', models.CharField(blank=True, max_length=100)),
                ('stars', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('clone_status', models.CharField(choices=[('pending', 'Pending'), ('cloning', 'Cloning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('clone_path', models.CharField(blank=True, max_length=500)),
                ('last_cloned_at', models.DateTimeField(blank=True, null=True)),
                ('clone_error', models.TextField(blank=True)),
                ('codebase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_repos', to='codebase.codebase')),
                ('connected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_repos', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='github_integration.githubintegration')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'github_repositories',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'repo_full_name')},
            },
        ),
    ]
