# Generated by Django 4.2.17 on 2026-03-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasources', '0001_initial'),
        ('projects', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_type', models.CharField(choices=[('support_ticket', 'Support Ticket'), ('interview_transcript', 'Interview Transcript'), ('feature_request', 'Feature Request'), ('nps_survey', 'NPS Survey'), ('churn_feedback', 'Churn Feedback'), ('slack_thread', 'Slack Thread'), ('analytics_event', 'Analytics Event'), ('session_replay', 'Session Replay'), ('custom', 'Custom')], max_length=50)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('text', models.TextField()),
                ('customer_segment', models.CharField(choices=[('enterprise', 'Enterprise'), ('mid_market', 'Mid-Market'), ('smb', 'SMB'), ('startup', 'Startup'), ('individual', 'Individual'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('source_name', models.CharField(blank=True, help_text='e.g., zendesk, intercom', max_length=100)),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('mixed', 'Mixed')], default='neutral', max_length=20)),
                ('urgency', models.IntegerField(default=5, help_text='1-10 scale')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('pain_points', models.JSONField(blank=True, default=list)),
                ('key_quotes', models.JSONField(blank=True, default=list)),
                ('topics', models.JSONField(blank=True, default=list)),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='datasources.datasource')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'raw_evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(blank=True)),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('content_text', models.TextField(blank=True, help_text='Extracted text content')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='evidence.rawevidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'evidence_attachments',
            },
        ),
    ]
