# Generated by Django 4.2.17 on 2026-03-14 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codebase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('zip', 'ZIP Upload'), ('tar', 'TAR.GZ Upload'), ('git', 'Git Repository')], default='zip', max_length=20)),
                ('storage_path', models.CharField(blank=True, max_length=500)),
                ('git_url', models.URLField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('file_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_codebases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'codebases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trend_summary', models.TextField(blank=True)),
                ('emerging_features', models.JSONField(blank=True, default=list)),
                ('competitor_features', models.JSONField(blank=True, default=list)),
                ('market_gap_opportunities', models.JSONField(blank=True, default=list)),
                ('industry_trends', models.JSONField(blank=True, default=list)),
                ('analysis_context', models.TextField(blank=True, help_text='Product context used for analysis')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'market_trends',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureDiscovery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature_name', models.CharField(max_length=500)),
                ('problem_statement', models.TextField()),
                ('evidence_links', models.JSONField(blank=True, default=list)),
                ('code_integration_points', models.JSONField(blank=True, default=list)),
                ('implementation_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20)),
                ('execution_plan', models.TextField(blank=True)),
                ('expected_impact', models.JSONField(blank=True, default=dict)),
                ('trend_alignment', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(choices=[('evidence', 'Evidence-Driven'), ('code', 'Code-Aware'), ('trend', 'Trend-Driven'), ('combined', 'Combined Analysis')], default='combined', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'feature_discoveries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodebaseAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('system_summary', models.TextField(blank=True)),
                ('major_modules', models.JSONField(blank=True, default=list)),
                ('existing_features', models.JSONField(blank=True, default=list)),
                ('api_endpoints', models.JSONField(blank=True, default=list)),
                ('database_models', models.JSONField(blank=True, default=list)),
                ('capability_map', models.JSONField(blank=True, default=dict)),
                ('technology_stack', models.JSONField(blank=True, default=list)),
                ('architecture_patterns', models.JSONField(blank=True, default=list)),
                ('file_structure', models.JSONField(blank=True, default=dict)),
                ('code_samples', models.JSONField(blank=True, default=dict, help_text='Key code snippets used for analysis')),
                ('error_message', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('codebase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='codebase.codebase')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'codebase_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
