# Generated by Django 4.2.17 on 2026-03-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codebaseanalysis',
            name='competitor_comparison',
            field=models.JSONField(blank=True, default=dict, help_text='Competitor feature comparison data'),
        ),
        migrations.AddField(
            model_name='codebaseanalysis',
            name='improvement_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='codebaseanalysis',
            name='missing_capabilities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='codebaseanalysis',
            name='new_feature_opportunities',
            field=models.JSONField(blank=True, default=list, help_text='AI-suggested new features based on codebase analysis'),
        ),
    ]
