# Generated by Django 4.2.17 on 2026-03-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('evidence_summarizer', 'Evidence Summarizer'), ('insight_clustering', 'Insight Clustering'), ('opportunity_discovery', 'Opportunity Discovery'), ('opportunity_scoring', 'Opportunity Scoring'), ('spec_generator', 'Spec Generator'), ('impact_prediction', 'Impact Prediction'), ('what_to_build', 'What To Build Next'), ('spec_chat', 'Spec Conversational Edit')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('tokens_used', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'agent_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent_type', models.CharField(choices=[('evidence_summarizer', 'Evidence Summarizer'), ('insight_clustering', 'Insight Clustering'), ('opportunity_discovery', 'Opportunity Discovery'), ('opportunity_scoring', 'Opportunity Scoring'), ('spec_generator', 'Spec Generator'), ('impact_prediction', 'Impact Prediction'), ('what_to_build', 'What To Build Next'), ('spec_chat', 'Spec Conversational Edit')], max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('prompt_template', models.TextField()),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'product_prompts',
                'ordering': ['-version'],
                'unique_together': {('project', 'agent_type', 'version')},
            },
        ),
    ]
