# Generated by Django 4.2.17 on 2026-03-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('opportunities', '0001_initial'),
        ('projects', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artifact_type', models.CharField(choices=[('prd', 'PRD'), ('user_stories', 'User Stories'), ('technical_spec', 'Technical Spec'), ('api_design', 'API Design'), ('qa_plan', 'QA Plan')], max_length=50)),
                ('title', models.CharField(max_length=500)),
                ('current_version', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('approved', 'Approved'), ('implementation', 'Implementation'), ('shipped', 'Shipped')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='opportunities.opportunity')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'generated_artifacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArtifactVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.IntegerField(default=1)),
                ('content', models.JSONField(default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('readiness_score', models.FloatField(default=0)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='specs.generatedartifact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'artifact_versions',
                'ordering': ['-version_number'],
                'unique_together': {('artifact', 'version_number')},
            },
        ),
    ]
