# Generated by Django 4.2.17 on 2026-03-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0001_initial'),
        ('projects', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightCluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('frequency', models.IntegerField(default=1, help_text='How often this appears')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('segments_affected', models.JSONField(blank=True, default=list)),
                ('representative_quotes', models.JSONField(blank=True, default=list)),
                ('trend_direction', models.CharField(choices=[('rising', 'Rising'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=20)),
                ('confidence', models.FloatField(default=0.0, help_text='0-1 confidence score')),
                ('topics', models.JSONField(blank=True, default=list)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('evidence_refs', models.ManyToManyField(blank=True, related_name='insight_clusters', to='evidence.rawevidence')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'insight_clusters',
                'ordering': ['-frequency', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period', models.CharField(help_text='e.g., 2024-W01', max_length=50)),
                ('mention_count', models.IntegerField(default=0)),
                ('severity_score', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)ss_created', to=settings.AUTH_USER_MODEL)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='insights.insightcluster')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='projects.project')),
            ],
            options={
                'db_table': 'insight_trends',
                'ordering': ['-period'],
            },
        ),
    ]
