# Generated by Django 4.2.17 on 2026-03-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('opportunity_discovered', 'Opportunity Discovered'), ('spec_ready', 'Spec Ready for Review'), ('approval_requested', 'Approval Requested'), ('impact_report', 'Impact Report Generated'), ('agent_completed', 'Agent Completed'), ('comment_added', 'Comment Added'), ('mention', 'Mentioned')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('entity_type', models.CharField(blank=True, max_length=50)),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
